DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd;
USE bd;

CREATE TABLE Jugador(
	ID INT,
	NOMBRE VARCHAR(20),
	CONTRASEÑA VARCHAR(20),
	MAIL VARCHAR(50),
	PUNTOS INT,
	PRIMARY KEY(ID)
)ENGINE = InnoDB;

CREATE TABLE Carta(
	ID INT,
	PALABRA VARCHAR(20),
	BAN1 VARCHAR(20),
	BAN2 VARCHAR(20),
	BAN3 VARCHAR(20),
	DIFICULTAD VARCHAR(20),
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE Partida(
	ID INT,
	JUG1 INT,
	JUG2 INT,
	JUG3 INT,
	JUG4 INT,
	IDCARTA INT,
	PUN1 INT,
	PUN2 INT,
	PUN3 INT,
	PUN4 INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (JUG1) REFERENCES Jugador(ID),
	FOREIGN KEY (JUG2) REFERENCES Jugador(ID),
	FOREIGN KEY (JUG3) REFERENCES Jugador(ID),
	FOREIGN KEY (JUG4) REFERENCES Jugador(ID),
	FOREIGN KEY (IDCARTA) REFERENCES Carta(ID)
)ENGINE = InnoDB;

CREATE TABLE Lista(
	IDJUGADOR INT,
	IDCARTA INT,
	PUNTOS INT,
	FOREIGN KEY (IDJUGADOR) REFERENCES Jugador(ID),
	FOREIGN KEY (IDCARTA) REFERENCES Carta(ID)
)ENGINE = InnoDB;		
	
	

	
